### ISSUE TITLE
Env var cannot be set when using code approach?

### ISSUE THREAD

**Issue by robmarkcole** [aws-containers/hello-app-runner#4]
I get the option for setting env var when using ECR image but not when deploying from Github - please advise

**Comment by mreferre** [comment]
I *believe* what you are seeing is that IF you select `Source code` as the repository type *AND* you select the option to `use a configuration file` (i.e. `apprunner.yaml` in the root of the repo) THEN all vars need to be declared inside the file and cannot be specified in at deployment time anymore. In other words it's all or nothing (i.e. if you choose the file, everything needs to be in the file). It would be interesting to consider splitting this and let customers add variables at deployment time (either in addition of those in the config file or instead of putting them in the config file). If you confirm this is what you are seeing I would tweak the title and start tracking this.

**Comment by robmarkcole** [comment]
Hi @mreferre 

Since I use env var for auth strings etc these could not securely be included in `apprunner.yaml`, unless somehow passed in from a github secret

You suggestion of allowing env var at deploy time would allow a user to fork a repo, then run as is but just dropping in their own env var

**Comment by mreferre** [comment]
What you are saying makes a ton of sense to me. However the place where you add the variables is on the next screen. If you click next (where you are above) you should see the option. However, if on this screen you select `use configuration file` and click next, they won't be there anymore (basically the behavior I described above).

**Comment by robmarkcole** [comment]
Indeed I just saw that and removed the screenshot :)

**Comment by mreferre** [comment]
Cool. Yeah I figured that. The way I would use this enhancement would be to have an `apprunner.yaml` file with some of the core info such as the language runtime, etc and decoupling the env variable for convenience (not secrecy). [This is a simple demo app](https://github.com/aws-containers/votingapp) I published today and as you can see the `apprunner.yaml` file has a variable that describes the region of deployment for a DDB table. I wish I could decouple the core info from this variable (otherwise the user would need to commit a change in the repo to change the region). As I said this is more for workflow convenience than for protecting a secret value (that is, your use case is WAY MORE important).

**Comment by robmarkcole** [comment]
that decoupling does sound useful, you could quickly test an app on dev/prod db for example without code changes

**Comment by mreferre** [comment]
Fun fact: I entertained this entire conversation thinking I was on the [App Runner roadmap repo](https://github.com/aws/apprunner-roadmap/issues) :) 

If you want to open this issue there please go ahead and we will track it (but I can do that, don't want to steal more of your time).

**Comment by robmarkcole** [comment]
done, thanks!
